apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dev-handson-app
images:
  - name: dev-handson-backend
    newName: image-registry.openshift-image-registry.svc:5000/dev-handson-app/backend-app
    newTag: "9b8951cd5ee1d51af667f4e3382b17445b2fa4a8" # backend-image-tag
  - name: dev-handson-frontend
    newName: image-registry.openshift-image-registry.svc:5000/dev-handson-app/frontend-app

    newTag: "ef2cc5ab425ebdec2d32cf6643430b55dc3debb6" # frontend-image-tag
