apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dev-handson
images:
  - name: dev-handson-backend
    newName: image-registry.openshift-image-registry.svc:5000/dev-handson/dev-handson-backend
    newTag: "281c25a1577b2a73a2d687efd7860bf221722116" # backend-image-tag
  - name: dev-handson-frontend
    newName: image-registry.openshift-image-registry.svc:5000/dev-handson/dev-handson-frontend
    newTag: "de51f035305864de50fbaf509a1012dfc9c5c438" # frontend-image-tag
